language: node_js
node_js:
  - 11

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  npm: true
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test
